#!/bin/bash

# Copyright (C) 2015 Yiqun Zhang <zhangyiqun9164@gmail.com>
# All Rights Reserved.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

echo "Loading 1M dataset..."
scidbtime "store(load2d('/home/scidb/kdd.bin', 1000000, 39), kdd1m);"
echo "Loading 10M dataset..."
scidbtime "store(load2d('/home/scidb/kdd.bin', 10000000, 39), kdd10m);"
echo "Loading 100M dataset..."
scidbtime "store(load2d('/home/scidb/kdd.bin', 100000000, 39), kdd100m);"
