DROP TABLE IF EXISTS n001Md08k04;
DROP TABLE IF EXISTS n001Md08k08;
DROP TABLE IF EXISTS n001Md08k16;
DROP TABLE IF EXISTS n010Md08k04;
DROP TABLE IF EXISTS n010Md08k08;
DROP TABLE IF EXISTS n010Md08k16;
DROP TABLE IF EXISTS n001Md08k04_import;
DROP TABLE IF EXISTS n001Md08k08_import;
DROP TABLE IF EXISTS n001Md08k16_import;
DROP TABLE IF EXISTS n010Md08k04_import;
DROP TABLE IF EXISTS n010Md08k08_import;
DROP TABLE IF EXISTS n010Md08k16_import;

DROP TABLE IF EXISTS XV;
DROP TABLE IF EXISTS CH;
DROP TABLE IF EXISTS NMQ;
DROP TABLE IF EXISTS WCR;
DROP TABLE IF EXISTS YNN;
DROP TABLE IF EXISTS YD;
DROP TABLE IF EXISTS model;


CREATE TABLE n001Md08k04 (
    i INTEGER PRIMARY KEY,
    incr_step INTEGER NOT NULL,
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
) SEGMENTED BY MODULARHASH(i) ALL NODES;

CREATE TABLE n001Md08k08 (
    i INTEGER PRIMARY KEY,
    incr_step INTEGER NOT NULL,
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
) SEGMENTED BY MODULARHASH(i) ALL NODES;

CREATE TABLE n001Md08k16 (
    i INTEGER PRIMARY KEY,
    incr_step INTEGER NOT NULL,
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
) SEGMENTED BY MODULARHASH(i) ALL NODES;

CREATE TABLE n010Md08k04 (
    i INTEGER PRIMARY KEY,
    incr_step INTEGER NOT NULL,
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
) SEGMENTED BY MODULARHASH(i) ALL NODES;

CREATE TABLE n010Md08k08 (
    i INTEGER PRIMARY KEY,
    incr_step INTEGER NOT NULL,
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
) SEGMENTED BY MODULARHASH(i) ALL NODES;

CREATE TABLE n010Md08k16 (
    i INTEGER PRIMARY KEY,
    incr_step INTEGER NOT NULL,
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
) SEGMENTED BY MODULARHASH(i) ALL NODES;

CREATE TABLE n001Md08k04_import (
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
);

CREATE TABLE n001Md08k08_import (
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
);

CREATE TABLE n001Md08k16_import (
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
);

CREATE TABLE n010Md08k04_import (
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
);

CREATE TABLE n010Md08k08_import (
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
);

CREATE TABLE n010Md08k16_import (
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
);

-- Centers in horizontal form
CREATE TABLE CH (
    j INTEGER NOT NULL,
    X1 FLOAT NOT NULL,
    X2 FLOAT NOT NULL,
    X3 FLOAT NOT NULL,
    X4 FLOAT NOT NULL,
    X5 FLOAT NOT NULL,
    X6 FLOAT NOT NULL,
    X7 FLOAT NOT NULL,
    X8 FLOAT NOT NULL
);

-- X in vertical form
CREATE TABLE XV (
    i INTEGER NOT NULL,
    l INTEGER NOT NULL,
    val FLOAT NOT NULL
) SEGMENTED BY MODULARHASH(i) ALL NODES;

CREATE TABLE WCR (
    l INTEGER NOT NULL,
    j INTEGER NOT NULL,
    W FLOAT NOT NULL DEFAULT 0,
    C FLOAT NOT NULL DEFAULT 0,
    R FLOAT NOT NULL DEFAULT 0
);

-- sufficient statistics
CREATE TABLE NMQ (
    l INTEGER NOT NULL,
    j INTEGER NOT NULL,
    N INTEGER NOT NULL,
    M FLOAT NOT NULL,
    Q FLOAT NOT NULL
)

CREATE TABLE YNN (
    i INTEGER NOT NULL,
    j INTEGER NOT NULL
);

CREATE TABLE YD (
    i INTEGER NOT NULL,
    d1 FLOAT NOT NULL,
    d2 FLOAT NOT NULL,
    d3 FLOAT NOT NULL,
    d4 FLOAT NOT NULL
)

CREATE TABLE model (
    n INTEGER NOT NULL,
    k INTEGER NOT NULL,
    omega FLOAT NOT NULL
);